language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29

jdk:
    - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-29"

script:
  ./gradlew build